In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import mpl_toolkits
%matplotlib inline
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [87]:
data=pd.read_csv('heart_failure_clinical_records_dataset.csv')
data.head(5)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_sodium  sex  smoking  time  \
0                    1  265000.00           130    1        0     4   
1                    0  263358.03           136    1        0     6   
2                    0  162000.00           129    1        1     7   
3                    0  210000.00           137    1        0     7   
4                    0  327000.00           116    0        0     8   

   serum_creatinine  DEATH_EVENT  
0               1.9            1  
1               1.1            1  
2               1.3            1  
3               1.9            1  
4               2.7            1

In [88]:
#data seperation
X= data.iloc[:,0:12]
y = data.iloc[:,12:]

#normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
scaled_df = pd.DataFrame(data=X_scaled, columns=X.columns)
scaled_df.head()


     

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  0.636364      0.0                  0.071319       0.0           0.090909   
1  0.272727      0.0                  1.000000       0.0           0.363636   
2  0.454545      0.0                  0.015693       0.0           0.090909   
3  0.181818      1.0                  0.011227       0.0           0.090909   
4  0.454545      1.0                  0.017479       1.0           0.090909   

   high_blood_pressure  platelets  serum_sodium  sex  smoking      time  \
0                  1.0   0.290823      0.485714  1.0      0.0  0.000000   
1                  0.0   0.288833      0.657143  1.0      0.0  0.007117   
2                  0.0   0.165960      0.457143  1.0      1.0  0.010676   
3                  0.0   0.224148      0.685714  1.0      0.0  0.010676   
4                  0.0   0.365984      0.085714  0.0      0.0  0.014235   

   serum_creatinine  
0          0.157303  
1          0.067416  
2          0.089888  
3          0.157303  
4          0.247191

In [89]:
#data split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=2)

In [90]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

# Transforming with the scaler function
X_scaled = pd.DataFrame(min_max_scaler.fit_transform(X))

# Printing the output
X_scaled.head()

0    1         2    3         4    5         6         7    8    9   \
0  0.636364  0.0  0.071319  0.0  0.090909  1.0  0.290823  0.485714  1.0  0.0   
1  0.272727  0.0  1.000000  0.0  0.363636  0.0  0.288833  0.657143  1.0  0.0   
2  0.454545  0.0  0.015693  0.0  0.090909  0.0  0.165960  0.457143  1.0  1.0   
3  0.181818  1.0  0.011227  0.0  0.090909  0.0  0.224148  0.685714  1.0  0.0   
4  0.454545  1.0  0.017479  1.0  0.090909  0.0  0.365984  0.085714  0.0  0.0   

         10        11  
0  0.000000  0.157303  
1  0.007117  0.067416  
2  0.010676  0.089888  
3  0.010676  0.157303  
4  0.014235  0.247191

In [114]:
# hard voting classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
log_clf = LogisticRegression(solver='lbfgs')
rnd_clf = RandomForestClassifier(n_estimators=100)
svm_clf = SVC(gamma='scale')
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')

In [115]:
# measure the algorithm performance using 10-fold cross validation
from sklearn.model_selection import cross_val_score
for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
    hard_voting_score = cross_val_score(voting_clf, X, y, scoring = 'accuracy', cv=10)
    print(clf.__class__.__name__, hard_voting_score.mean())

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sa

LogisticRegression 0.775632183908046


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sa

RandomForestClassifier 0.7689655172413794


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sa

SVC 0.775632183908046


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sa

VotingClassifier 0.7822988505747126


In [93]:
# measure the algorithm performance using 10-fold cross validation
from sklearn.model_selection import cross_val_score
for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
    hard_voting_score = cross_val_score(voting_clf, X_test, y_test
                                        , scoring = 'accuracy', cv=10)
    print(clf.__class__.__name__, hard_voting_score.mean())

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression 0.8666666666666666


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example 

RandomForestClassifier 0.8444444444444443


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example 

SVC 0.8555555555555555


C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

VotingClassifier 0.8222222222222222


In [94]:
from sklearn.linear_model import LogisticRegression

log_reg_model = LogisticRegression()

# Fitting a logistic regression model on the training set
log_reg_model.fit(X_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [95]:

pred = log_reg_model.predict(X_test)
print("Accuracy of Logistic regression model prediction on test set: {:.2f}".format(log_reg_model.score(X_test, y_test)))

Accuracy of Logistic regression model prediction on test set: 0.86


In [96]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Confusion Matrix for the model
print(confusion_matrix(y_test, pred))

# Classification report for the model
print(classification_report(y_test, pred))

[[60  6]
 [ 7 17]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90        66
           1       0.74      0.71      0.72        24

    accuracy                           0.86        90
   macro avg       0.82      0.81      0.81        90
weighted avg       0.85      0.86      0.85        90



In [97]:
#Ensemble Model Using the Averaging Technique:

In [98]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [99]:
# Defining the three base models. 

model1 = LogisticRegression(random_state = 20)
model2 = KNeighborsClassifier(n_neighbors = 5)
model3 = RandomForestClassifier(n_estimators = 500)

In [100]:
# Fitting all three models on the training data

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\user\AppData\Local\Temp\ipykernel_2276\1475861958.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(X_train, y_train)


RandomForestClassifier(n_estimators=500)

In [101]:
# predicting the probabilities of each model on the test set

pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)

In [102]:
ensemble_pred=(pred1 + pred2 + pred3)/3

In [103]:
ensemble_pred=ensemble_pred.round()

In [104]:
pred


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0], dtype=int64)

In [105]:
#prediction output has two columns corresponding to each class - Printing the order of classes for each model

print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [106]:
confusion_Matrix = confusion_matrix(y_test, ensemble_pred)
print(confusion_Matrix)

[[63  3]
 [ 7 17]]


In [107]:
# generating classification report

from sklearn.metrics import classification_report
print(classification_report(y_test, ensemble_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.93        66
           1       0.85      0.71      0.77        24

    accuracy                           0.89        90
   macro avg       0.88      0.83      0.85        90
weighted avg       0.89      0.89      0.89        90



In [108]:
#Ensemble Model Using the Weighted Averaging Technique
#In the weighted averaging method, weights are assigned arbitrarily based on our judgment of each of the predictions
# weights are assigned  that the sum of all weights becomes 1 
# Calculating the ensemble prediction by applying weights for each prediction

ensemble_pred1 = (pred1 * 0.60 + pred2 * 0.20 + pred3 * 0.20)

In [109]:
ensemble_pred1= ensemble_pred.round()

In [110]:
print(model1.classes_)
print(model2.classes_)
print(model3.classes_)

[0 1]
[0 1]
[0 1]


In [116]:
confusionMatrix = confusion_matrix(y_test, ensemble_pred1)
print(confusionMatrix)
print(classification_report(y_test, ensemble_pred1))

[[63  3]
 [ 7 17]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.93        66
           1       0.85      0.71      0.77        24

    accuracy                           0.89        90
   macro avg       0.88      0.83      0.85        90
weighted avg       0.89      0.89      0.89        90



In [117]:
#Max Voting Method
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# models
model1 = LogisticRegression(random_state= 20)
model2 = KNeighborsClassifier(n_neighbors= 6)
model3 = RandomForestClassifier(n_estimators=500)
model = VotingClassifier(estimators=[( 'lr', model1),( 'knn', model2),( 'rf',model3)], voting= 'hard')

In [118]:
model.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


VotingClassifier(estimators=[('lr', LogisticRegression(random_state=20)),
                             ('knn', KNeighborsClassifier(n_neighbors=6)),
                             ('rf', RandomForestClassifier(n_estimators=500))])

In [120]:
# predicting accuracy score on the test set

model.score(X_test, y_test)

0.8777777777777778

In [121]:
# Generating the predictions on the test set

preds1 = model.predict(X_test)

In [122]:
preds1.shape

(90,)

In [123]:

print(confusion_matrix(y_test, preds1))


[[63  3]
 [ 8 16]]


In [124]:
# classification report for Max Voting Technique

print(classification_report(y_test, preds1)

SyntaxError: unexpected EOF while parsing (1167919824.py, line 3)

In [126]:
#Max Voting Method
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# models
model1 = LogisticRegression(random_state= 20)
model2 = KNeighborsClassifier(n_neighbors= 6)
model3 = RandomForestClassifier(n_estimators=500)
model5 = VotingClassifier(estimators=[( 'lr', model1),( 'knn', model2),( 'rf',model3)], voting= 'soft')

In [128]:
model5.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\user\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


VotingClassifier(estimators=[('lr', LogisticRegression(random_state=20)),
                             ('knn', KNeighborsClassifier(n_neighbors=6)),
                             ('rf', RandomForestClassifier(n_estimators=500))],
                 voting='soft')

In [129]:
model5.score(X_test, y_test)

0.8555555555555555

In [130]:
#Ensemble Learning with Bagging Method
# Defining the base learner

from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(random_state = 50)
from sklearn.ensemble import BaggingClassifier

bagging_learner = BaggingClassifier(base_estimator = random_forest_model, n_estimators= 10, max_samples=0.6, max_features= 0.6)

model = bagging_learner.fit(X_train, y_train)
pred = model.predict(X_test)
print(confusion_matrix(y_test, pred))

C:\Users\user\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:719: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[63  3]
 [ 6 18]]


In [131]:
# Printing the classification report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93        66
           1       0.86      0.75      0.80        24

    accuracy                           0.90        90
   macro avg       0.89      0.85      0.87        90
weighted avg       0.90      0.90      0.90        90



In [132]:

# Defining the base learner

model_logistic_reg = LogisticRegression(random_state = 50)
from sklearn.ensemble import AdaBoostClassifier
boosting_model = AdaBoostClassifier(base_estimator = model_logistic_reg, n_estimators= 200)
fitted_model = boosting_model.fit(X_train, y_train)
pred = fitted_model.predict(X_test)


print(confusion_matrix(y_test, pred))

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[59  7]
 [ 7 17]]


In [133]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        66
           1       0.71      0.71      0.71        24

    accuracy                           0.84        90
   macro avg       0.80      0.80      0.80        90
weighted avg       0.84      0.84      0.84        90



In [47]:
# Importing the meta learner (logistic regression) and base learners (knn and random forest)

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from mlxtend.classifier import StackingClassifier

base_learner_knn= KNeighborsClassifier(n_neighbors = 5)
base_learner_random_forest = RandomForestClassifier(random_state = 50)
meta_learner_log_reg = LogisticRegression(random_state = 50)

stackclf = StackingClassifier(classifiers=[base_learner_knn,base_learner_random_forest],
meta_classifier= meta_learner_log_reg)

main_model = stackclf.fit(X_train, y_train)

pred = model.predict(X_test)

print(confusion_matrix(y_test, pred))

ModuleNotFoundError: No module named 'mlxtend'